name: Example workflow to exercise action
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Fetch slideshow.author from httpbin.org
      id: fetchjson  
      uses: ./
      with:
        url: 'https://httpbin.org/json'
        property-path: slideshow.author
    - name: Echo slideshow.author's value
      run: echo ${{ steps.fetchjson.outputs.value }}
